# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confparse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='confparse.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63onfparse.proto\"A\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\"^\n\x0eSingleLineSpec\x12\x11\n\tline_spec\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x02 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x03 \x01(\t\x12\x1a\n\x04type\x18\x04 \x01(\x0e\x32\x0c.RequestType\"s\n\rMultiLineSpec\x12\x13\n\x0bparent_spec\x18\x01 \x01(\t\x12\x12\n\nchild_spec\x18\x02 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x03 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x04 \x01(\t\x12\x1a\n\x04type\x18\x05 \x01(\x0e\x32\x0c.RequestType*b\n\x0bRequestType\x12\r\n\tfind_line\x10\x00\x12\x18\n\x14\x66ind_parents_w_child\x10\x01\x12\x19\n\x15\x66ind_parents_wo_child\x10\x02\x12\x0f\n\x0b\x66ind_blocks\x10\x03\x32\xc3\x01\n\x06Parser\x12\'\n\tfind_line\x12\x0f.SingleLineSpec\x1a\t.Response\x12)\n\x0b\x66ind_blocks\x12\x0f.SingleLineSpec\x1a\t.Response\x12\x31\n\x14\x66ind_parents_w_child\x12\x0e.MultiLineSpec\x1a\t.Response\x12\x32\n\x15\x66ind_parents_wo_child\x12\x0e.MultiLineSpec\x1a\t.Responseb\x06proto3')
)

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='find_line', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='find_parents_w_child', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='find_parents_wo_child', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='find_blocks', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=299,
  serialized_end=397,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
find_line = 0
find_parents_w_child = 1
find_parents_wo_child = 2
find_blocks = 3



_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Response.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Response.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='Response.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=84,
)


_SINGLELINESPEC = _descriptor.Descriptor(
  name='SingleLineSpec',
  full_name='SingleLineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_spec', full_name='SingleLineSpec.line_spec', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delim', full_name='SingleLineSpec.delim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='SingleLineSpec.config', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='SingleLineSpec.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=180,
)


_MULTILINESPEC = _descriptor.Descriptor(
  name='MultiLineSpec',
  full_name='MultiLineSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent_spec', full_name='MultiLineSpec.parent_spec', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='child_spec', full_name='MultiLineSpec.child_spec', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delim', full_name='MultiLineSpec.delim', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='MultiLineSpec.config', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MultiLineSpec.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=297,
)

_SINGLELINESPEC.fields_by_name['type'].enum_type = _REQUESTTYPE
_MULTILINESPEC.fields_by_name['type'].enum_type = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['SingleLineSpec'] = _SINGLELINESPEC
DESCRIPTOR.message_types_by_name['MultiLineSpec'] = _MULTILINESPEC
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'confparse_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

SingleLineSpec = _reflection.GeneratedProtocolMessageType('SingleLineSpec', (_message.Message,), dict(
  DESCRIPTOR = _SINGLELINESPEC,
  __module__ = 'confparse_pb2'
  # @@protoc_insertion_point(class_scope:SingleLineSpec)
  ))
_sym_db.RegisterMessage(SingleLineSpec)

MultiLineSpec = _reflection.GeneratedProtocolMessageType('MultiLineSpec', (_message.Message,), dict(
  DESCRIPTOR = _MULTILINESPEC,
  __module__ = 'confparse_pb2'
  # @@protoc_insertion_point(class_scope:MultiLineSpec)
  ))
_sym_db.RegisterMessage(MultiLineSpec)



_PARSER = _descriptor.ServiceDescriptor(
  name='Parser',
  full_name='Parser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=400,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_line',
    full_name='Parser.find_line',
    index=0,
    containing_service=None,
    input_type=_SINGLELINESPEC,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_blocks',
    full_name='Parser.find_blocks',
    index=1,
    containing_service=None,
    input_type=_SINGLELINESPEC,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_parents_w_child',
    full_name='Parser.find_parents_w_child',
    index=2,
    containing_service=None,
    input_type=_MULTILINESPEC,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_parents_wo_child',
    full_name='Parser.find_parents_wo_child',
    index=3,
    containing_service=None,
    input_type=_MULTILINESPEC,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARSER)

DESCRIPTOR.services_by_name['Parser'] = _PARSER

# @@protoc_insertion_point(module_scope)
