# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import configparser.confparse_pb2 as confparse__pb2


class ParserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.find_line = channel.unary_unary(
        '/Parser/find_line',
        request_serializer=confparse__pb2.SingleLineSpec.SerializeToString,
        response_deserializer=confparse__pb2.Response.FromString,
        )
    self.find_blocks = channel.unary_unary(
        '/Parser/find_blocks',
        request_serializer=confparse__pb2.SingleLineSpec.SerializeToString,
        response_deserializer=confparse__pb2.Response.FromString,
        )
    self.find_parents_w_child = channel.unary_unary(
        '/Parser/find_parents_w_child',
        request_serializer=confparse__pb2.MultiLineSpec.SerializeToString,
        response_deserializer=confparse__pb2.Response.FromString,
        )
    self.find_parents_wo_child = channel.unary_unary(
        '/Parser/find_parents_wo_child',
        request_serializer=confparse__pb2.MultiLineSpec.SerializeToString,
        response_deserializer=confparse__pb2.Response.FromString,
        )


class ParserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def find_line(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_blocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_parents_w_child(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_parents_wo_child(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'find_line': grpc.unary_unary_rpc_method_handler(
          servicer.find_line,
          request_deserializer=confparse__pb2.SingleLineSpec.FromString,
          response_serializer=confparse__pb2.Response.SerializeToString,
      ),
      'find_blocks': grpc.unary_unary_rpc_method_handler(
          servicer.find_blocks,
          request_deserializer=confparse__pb2.SingleLineSpec.FromString,
          response_serializer=confparse__pb2.Response.SerializeToString,
      ),
      'find_parents_w_child': grpc.unary_unary_rpc_method_handler(
          servicer.find_parents_w_child,
          request_deserializer=confparse__pb2.MultiLineSpec.FromString,
          response_serializer=confparse__pb2.Response.SerializeToString,
      ),
      'find_parents_wo_child': grpc.unary_unary_rpc_method_handler(
          servicer.find_parents_wo_child,
          request_deserializer=confparse__pb2.MultiLineSpec.FromString,
          response_serializer=confparse__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Parser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
